# Generated by Django 5.1.4 on 2024-12-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
