# Generated by Django 5.1.4 on 2024-12-22 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(help_text="Тема сообщения", max_length=100),
                ),
                ("letter", models.TextField(verbose_name="Тело письма")),
            ],
            options={
                "verbose_name": "Письмо",
                "verbose_name_plural": "Письма",
                "ordering": ["subject"],
            },
        ),
        migrations.CreateModel(
            name="Recipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        help_text="Введите почту получателя рассылки",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        help_text="Введите полное имя получателя",
                        max_length=100,
                        verbose_name="ФИО",
                    ),
                ),
                (
                    "comment",
                    models.TextField(verbose_name="Введите комментарий о получателе"),
                ),
            ],
            options={
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
                "ordering": ["email"],
            },
        ),
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_shipment",
                    models.DateTimeField(
                        help_text="Дата и время первой отправки рассылки"
                    ),
                ),
                (
                    "last_dispatch",
                    models.DateTimeField(
                        help_text="Дата и время окончания отправки рассылки"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("завершена", "Завершена"),
                            ("создана", "Создана"),
                            ("запущена", "Запущена"),
                        ],
                        default="создана",
                        max_length=20,
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mailings.message",
                    ),
                ),
                ("recipients", models.ManyToManyField(to="mailings.recipient")),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
                "ordering": ["message", "status"],
            },
        ),
        migrations.CreateModel(
            name="MailingAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_of_attempt",
                    models.DateTimeField(help_text="Дата и время  попытки  рассылки"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("успешно", "Успешно"), ("не успешно", "Не успешно")],
                        default="успешно",
                        max_length=20,
                    ),
                ),
                (
                    "mail_reply",
                    models.TextField(verbose_name="Ответ почтового сервера "),
                ),
                (
                    "newsletter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mailings.newsletter",
                    ),
                ),
            ],
        ),
    ]
