# Generated by Django 5.1.4 on 2024-12-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipient",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="users/photo"),
        ),
    ]
