# Generated by Django 5.1.4 on 2024-12-28 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0002_recipient_avatar"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["letter"],
                "verbose_name": "Письмо",
                "verbose_name_plural": "Письма",
            },
        ),
    ]
