# Generated by Django 5.1.4 on 2025-01-06 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0005_message_owner_newsletter_owner_recipient_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newsletter",
            options={
                "ordering": ["message", "status"],
                "permissions": [("can_unpublish", "Can unpublish ")],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
